version: 2

jobs:
  build:
    docker:
      - image: python:3.6.5-alpine
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            pip install pipenv
            apk add --update --no-cache alpine-sdk
            pipenv install --deploy --system
      - run:
          name: Run test
          command: |
            python test_hconfig.py
