version: 2

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            sudo pip install pipenv
            sudo pipenv install --deploy --system
      - run:
          name: Run test
          command: |
            python test_hconfig.py
